name: Build and Deploy Nick's Personal Site

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy Site
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run deploy
